services:
  postgres:
    image: postgres:16-alpine
    container_name: payment-processor-db
    environment:
      POSTGRES_DB: payment_processor
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payment_processor"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: payment-processor-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_processor
      SPRING_DATASOURCE_USERNAME: payment_user
      SPRING_DATASOURCE_PASSWORD: payment_pass
    ports:
      - "8080:8080"

volumes:
  postgres_data:
